### ISSUE TITLE
UI to Re-Activate PODS

### ISSUE THREAD

**Issue by miklb** [hurricane-response/florence-api#40]
if a POD is de-activated, there is no UI to resurface that location.

**Comment by omnilord** [comment]
Is there a means of viewing de-activated shelters?

**Comment by nihonjinrxs** [comment]
terminology is a bit different there. on shelters `active=false` is the same as `archived=true` on the distribution points. I couldn't use `active` in the same way for PODs since FEMA uses it differently, but I figured eventually, we'd migrate shelters to the same terminology, but that was a tomorrow problem.
